[tox]
envlist = py39-ansible213, py39-ansible214, py39-ansible215
skipsdist = true

[testenv]
deps =
    molecule==6.0.3
    molecule-podman==2.0.3
    ansible213: ansible-core==2.13.12
    ansible214: ansible-core==2.14.10
    ansible215: ansible-core==2.15.10
commands_pre =
    ansible-galaxy collection install containers.podman
commands =
    {posargs:molecule test -s podman --destroy always}
